# Generated by Django 2.1.7 on 2019-03-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='last modified')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('slug', models.SlugField(allow_unicode=True, max_length=1000, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('entry', models.CharField(blank=True, max_length=255, verbose_name='Entry')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('old_id', models.IntegerField(default=0, verbose_name='OldId')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='last modified')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('slug', models.SlugField(allow_unicode=True, max_length=1000, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('status', models.CharField(choices=[('new', 'New'), ('current', 'Current'), ('suspend', 'Suspend'), ('done', 'Done'), ('cancel', 'Canceled')], default='new', max_length=255, verbose_name='Status')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Time start')),
                ('due', models.DateTimeField(blank=True, null=True, verbose_name='Time due')),
                ('time_required', models.IntegerField(blank=True, null=True, verbose_name='Time required')),
                ('time_spent', models.IntegerField(blank=True, null=True, verbose_name='Time spent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-id'],
            },
        ),
    ]
