version: "3"

services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    hostname: postgresql
    env_file:
      - prod.env
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - 6543:5432

  backend:
    restart: always
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/srv/erp_chzso_2/backend
      - ./frontend/static/builds:/srv/erp_chzso_2/frontend/static/builds
    depends_on:
      - postgresql
    env_file: prod.env
    command: >
      bash -c '
      python manage.py makemigrations &&
      python manage.py migrate --run-syncdb &&
      python manage.py collectstatic --noinput &&
      uwsgi --ini uwsgi.ini'

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./frontend/staticfiles:/usr/share/nginx/static
      - ./backend/socket:/tmp/socket
    depends_on:
      - backend
    command: nginx -g 'daemon off';

