version: "3"

services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx
    ports:
      - 80:80
    depends_on:
      - backend
    command: nginx -g 'daemon off';

  backend:
    restart: always
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/srv/erp_chzso_2/backend
      - ./frontend/static:/srv/erp_chzso_2/frontend/static
    depends_on:
      - postgresql
    env_file: prod.env
    command: >
      bash -c '
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn main.wsgi -b 0.0.0.0:8080'

  postgresql:
    container_name: postgresql
    image: postgres:latest
    hostname: postgresql
    env_file:
      - prod.env
    ports:
      - 6543:5432
#    volumes:
#      - postgres_data_dev:/var/lib/postgresql/data
#      - postgres_backup_dev:/backups
