# Generated by Django 2.2.1 on 2019-05-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
